#!/bin/bash

# Do the conversion without root
/usr/bin/sudo -E -u user /usr/local/bin/document-to-pixels-unpriv

# Move converted files into /dangerzone
/usr/bin/mv /tmp/page-*.rgb /dangerzone
/usr/bin/mv /tmp/page-*.width /dangerzone
/usr/bin/mv /tmp/page-*.height /dangerzone
