#!/bin/bash

# Do the conversion without root
/usr/bin/sudo -E -u user /usr/local/bin/pixels-to-pdf-unpriv

# Move converted files into /safezone
/usr/bin/mv /tmp/safe-output.pdf /safezone
/usr/bin/mv /tmp/safe-output-compressed.pdf /safezone
